name: "Find PR"

on:
  workflow_call:
    outputs:
      found:
        value: ${{ jobs.pull-request.outputs.found }}
      base_ref:
        value: ${{ jobs.pull-request.outputs.base_ref }}
      base_sha:
        value: ${{ jobs.pull-request.outputs.base_sha }}
      head_ref:
        value: ${{ jobs.pull-request.outputs.head_ref }}
      head_sha:
        value: ${{ jobs.pull-request.outputs.head_sha }}

jobs:

  pull-request:
    name: "Find PR"
    runs-on: ubuntu-24.04
    timeout-minutes: 1

    permissions: {}

    outputs:
      found: ${{ steps.current-pr.outputs.number != null }}
      # Simulate github.event.pull_request.base.ref on push trigger.
      base_ref: ${{ steps.current-pr.outputs.number != null && fromJSON(steps.current-pr.outputs.pr).base.ref }}
      base_sha: ${{ steps.current-pr.outputs.number != null && fromJSON(steps.current-pr.outputs.pr).base.sha }}
      # Simulate github.event.pull_request.head.ref on push trigger.
      head_ref: ${{ steps.current-pr.outputs.number != null && fromJSON(steps.current-pr.outputs.pr).head.ref }}
      head_sha: ${{ steps.current-pr.outputs.number != null && fromJSON(steps.current-pr.outputs.pr).head.sha }}

    steps:

      - name: "Determine which PR this commit belongs to, so we can clone its base branch for comparison."
        id: current-pr
        uses: 8BitJonny/gh-get-current-pr@4.0.0

      - name: "Pull Request #${{ steps.current-pr.outputs.number }}"
        shell: bash
        run: >
          true
