name: "🧪 Screenshot Tests / Verify"

on:
  workflow_call

jobs:

  verify:
    name: "Verify"
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:

      - name: "Set up JDK 17."
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17

      - name: "Set up Android SDK."
        uses: android-actions/setup-android@v2

      - name: "Set up Android SDK components."
        run: |
          # The following are already done by setup-android@v2 action:
          # sdkmanager --install "cmdline-tools;latest"
          # sdkmanager --install "tools"
          # sdkmanager --install "platform-tools"

          # Install Android API used to build the project.
          echo sdkmanager --install "platforms;android-34"
          sdkmanager --install "platforms;android-34"

      - name: "Checkout ${{ needs.pull_request.outputs.head_ref }} branch in ${{ github.repository }} repository."
        uses: actions/checkout@v4
        with:
          ref: ${{ format('refs/heads/{0}', needs.pull_request.outputs.head_ref) }}

      - name: "Validate Gradle Wrapper JARs."
        uses: gradle/wrapper-validation-action@v1

      - name: "Download 'Screenshot Golden Values' artifact."
        uses: actions/download-artifact@v3
        with:
          name: 'Screenshot Golden Values'

      - name: "Run screenshot tests to verify ${{ needs.pull_request.outputs.head_ref }}."
        id: gradle
        run: >
          ./gradlew
          --no-daemon
          --no-build-cache
          --stacktrace
          --continue
          --scan
          verifyPaparazziDebug
          -Pnet.twisterrob.build.screenshot-tests=true

      - name: "Publish 'Gradle' commit status (with Build Scan URL)."
        if: (success() || failure()) && steps.gradle != null && steps.gradle.outputs.result-success != null
        uses: actions/github-script@v6
        with:
          debug: ${{ secrets.ACTIONS_STEP_DEBUG || false }}
          script: |
            await github.rest.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: context.sha,
              state: ${{ toJSON(fromJSON(steps.gradle.outputs.result-success)) }} === true ? "success" : "failure",
              context: "CI / Screenshot Tests / Verify / Gradle",
              description: ${{ toJSON(fromJSON(steps.gradle.outputs.result-text)) }},
              target_url: ${{ toJSON(fromJSON(steps.gradle.outputs.build-scan-url)) }}
            });

      - name: "Upload 'Screenshot Test Results' artifact."
        if: success() || failure()
        uses: actions/upload-artifact@v3
        with:
          name: 'Screenshot Test Results'
          # Notice that `${{ github.workspace }}/**/build/reports/paparazzi/` folder is not uploaded,
          # that's because Paparazzi doesn't generate a report on failure...
          path: |
            ${{ github.workspace }}/**/build/reports/tests/*/
            ${{ github.workspace }}/**/build/test-results/*/TEST-*.xml
            ${{ github.workspace }}/**/build/paparazzi/failures/delta-*.png
            ${{ github.workspace }}/**/build/paparazzi/failures/*.png

      - name: "Publish '🔔 Test: Screenshot Verify Results' check suite."
        if: success() || failure()
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          check_name: "🔔 Test: Screenshot Verify Results"
          comment_mode: off
          report_individual_runs: true
          test_changes_limit: 0
          junit_files: ${{ github.workspace }}/**/build/test-results/*/TEST-*.xml
