name: "📷 Screenshot Tests / 📸 Record"

on:
  workflow_call:
    inputs:

      ref:
        description: "The base branch to compare against."
        type: string
        required: false
        default: "main"

      golden_artifact:
        description: "The name of the artifact containing the golden values for all modules."
        type: string
        required: false
        default: 'Screenshot Golden Values'

jobs:

  record:
    name: "📸 Record"
    timeout-minutes: 20

    permissions:
      # actions/checkout
      contents: read
      # createCommitStatus
      statuses: write
      # EnricoMi/publish-unit-test-result-action
      checks: write

    defaults:
      run:
        shell: bash

    runs-on: ubuntu-latest
    steps:

      - name: "Set up JDK for Android SDK."
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      - name: "Set up Android SDK."
        uses: android-actions/setup-android@v3
        with:
          log-accepted-android-sdk-licenses: false

      - name: "Checkout ${{ inputs.ref }} branch in ${{ github.repository }} repository."
        uses: actions/checkout@v4
        with:
          ref: ${{ format('refs/heads/{0}', inputs.ref) }}

      - name: "Set up JDK for Project."
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version-file: .java-version

      - name: "Set up Gradle."
        uses: gradle/actions/setup-gradle@v3

      - name: "Record screenshots golden values for ${{ inputs.ref }}."
        id: gradle
        run: >
          ./gradlew
          --no-daemon
          --no-build-cache
          --stacktrace
          --continue
          --scan
          recordPaparazziDebug
          -Pnet.twisterrob.build.screenshot-tests=true

      - name: "Publish 'Gradle' commit status (with Build Scan URL)."
        if: ${{ (success() || failure()) && steps.gradle != null && steps.gradle.outputs.result-success != null }}
        env:
          RESULT_SUCCESS: ${{ fromJSON(steps.gradle.outputs.result-success) }}
          RESULT_TEXT: ${{ fromJSON(steps.gradle.outputs.result-text) }}
          BUILD_SCAN_URL: ${{ steps.gradle.outputs.build-scan-url }}
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: context.sha,
              state: process.env.RESULT_SUCCESS === 'true' ? "success" : "failure",
              context: "CI / Screenshot Tests / Record / Gradle",
              description: process.env.RESULT_TEXT,
              target_url: process.env.BUILD_SCAN_URL,
            });

      - name: "Upload '${{ inputs.golden_artifact }}' artifact."
        if: ${{ success() }}
        uses: actions/upload-artifact@v4
        with:
          name: '${{ inputs.golden_artifact }}'
          if-no-files-found: error
          path: |
            ${{ github.workspace }}/**/src/test/snapshots/images/*.png

      - name: "Upload 'Screenshot Record Results' artifact."
        if: ${{ success() || failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: 'Screenshot Record Results'
          if-no-files-found: error
          path: |
            ${{ github.workspace }}/**/build/reports/tests/*/
            ${{ github.workspace }}/**/build/reports/paparazzi/
            ${{ github.workspace }}/**/build/test-results/*/TEST-*.xml

      - name: "Publish '🔔 Test: Screenshot Record Results' check suite."
        if: ${{ success() || failure() }}
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          check_name: "🔔 Test: Screenshot Record Results"
          comment_mode: off
          report_individual_runs: true
          action_fail_on_inconclusive: true
          test_changes_limit: 0
          junit_files: ${{ github.workspace }}/**/build/test-results/*/TEST-*.xml
