name: "CI"

on:
  push

concurrency:
  # See https://github.com/TWiStErRob/github-workflows/blob/main/snippets/cancel-pr-ci-on-push.yml
  group: ${{ github.ref == 'refs/heads/main' && format('ci-main-{0}', github.sha) || format('ci-{0}', github.ref) }}
  cancel-in-progress: true

jobs:
  validate:
    name: "🦺 Validation"
    uses: TWiStErRob/github-workflows/.github/workflows/validate.yml@94f2ec4f96e146200f801fe7e09310c79cb2d2b3 # v2

  build:
    name: "🔨 Build & Verify"
    uses: ./.github/workflows/CI-build.yml
    needs:
      - validate

  prepare:
    name: "Prepare"
    uses: ./.github/workflows/CI-pr.yml
    # Don't execute on main, it'll never be PR'd.
    if: ${{ github.ref != 'refs/heads/main' && (success() || failure()) }}

  screenshot:
    name: "📷 Screenshot Tests"
    uses: ./.github/workflows/CI-screenshot.yml
    with:
      base_ref: ${{ needs.prepare.outputs.base_ref }}
      head_ref: ${{ needs.prepare.outputs.head_ref }}
    needs:
      - validate
      - prepare
    # Don't execute on main, as it'll just verify against itself.
    if: ${{ github.ref != 'refs/heads/main' && needs.prepare.outputs.found == 'true' }}
