name: CI
on:
  push
concurrency:
  # Documentation suggests ${{ github.head_ref }}, but that's only available on pull_request/pull_request_target triggers, so using ${{ github.ref }}.
  # On master, we want all builds to complete even if merging happens faster to make it easier to discover at which point something broke.
  # More info: https://stackoverflow.com/a/68422069/253468:
  group: ${{ github.ref == 'refs/heads/master' && format('ci-master-{0}', github.sha) || format('ci-{0}', github.ref) }}
  cancel-in-progress: true
jobs:
  build:
    name: 🔨 Build & Verify
    runs-on: ubuntu-latest
    # A local build took 20 seconds, CI takes 3 minutes with setup.
    # Because it's cloud, give it a bit of a buffer and constrain.
    timeout-minutes: 10
    steps:
      - name: Set up JDK 11.
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 11

      - name: Set up Android SDK.
        uses: android-actions/setup-android@v2

      - name: Set up Android SDK components.
        run: |
          # Uninstall NDK, because it's not used and it emits a warning:
          # Warning: Observed package id 'ndk;21.4.7075529' in inconsistent location '/usr/local/lib/android/sdk/ndk-bundle' (Expected '/usr/local/lib/android/sdk/ndk/21.4.7075529')
          echo sdkmanager --uninstall "ndk;21.4.7075529"
          sdkmanager --uninstall "ndk;21.4.7075529"

          # The following are already done by setup-android@v2 action:
          # sdkmanager --install "cmdline-tools;latest"
          # sdkmanager --install "tools"
          # sdkmanager --install "platform-tools"

          # Install Android API used to build the project.
          echo sdkmanager --install "platforms;android-31"
          sdkmanager --install "platforms;android-31"

      - name: Checkout ${{ github.ref }} branch in ${{ github.repository }} repository.
        uses: actions/checkout@v3

      - name: Build & Verify project using Gradle.
        run: >
          ./gradlew
          --no-daemon
          --no-build-cache
          --stacktrace
          --continue
          assemble
          check
          detektReportMergeSarif
          detektReportMergeXml
          lintReportMergeSarif
          violationReportHtml
          violationCountFile

      - name: Upload "Lint Results" artifact.
        if: success() || failure()
        uses: actions/upload-artifact@v3
        with:
          name: Lint Results
          path: |
            ${{ github.workspace }}/**/build/reports/lint-results*.html
            ${{ github.workspace }}/build/reports/violations.*
            ${{ github.workspace }}/build/reports/lint/merge-*.*

      - name: Fail if there are violations
        if: success() || failure()
        run: |
          count=$(cat "${{ github.workspace }}/build/reports/violations.count")
          if [[ "$count" != "0" ]]; then
            echo "There were $count violations"
            exit 1
          else
            echo "No violations found."
            exit 0
          fi

      - name: Publish "Code scanning results / Android Lint" (Debug).
        uses: github/codeql-action/upload-sarif@v2
        if: success() || failure()
        with:
          # merge-debug.sarif and merge-release.sarif in the folder.
          sarif_file: ${{ github.workspace }}/build/reports/lint/

      - name: Publish "Code scanning results / Android Lint" (Release).
        uses: github/codeql-action/upload-sarif@v2
        if: success() || failure()
        with:
          checkout_path: ${{ github.workspace }}
          sarif_file: ${{ github.workspace }}/build/reports/lint/merge-release.sarif

      - name: Upload "Unit Test Results" artifact.
        if: success() || failure()
        uses: actions/upload-artifact@v3
        with:
          name: Unit Test Results
          path: ${{ github.workspace }}/**/build/reports/tests/*/

      - name: Publish "Unit Results" check suite and "Unit Test Results" comment.
        if: success() || failure()
        uses: EnricoMi/publish-unit-test-result-action@v1
        with:
          check_name: "🔔 Test: Unit Results"
          comment_title: Unit Test Results
          report_individual_runs: true
          test_changes_limit: 0
          files: ${{ github.workspace }}/**/build/test-results/*/TEST-*.xml

      - name: Upload "Detekt Results" artifact.
        if: success() || failure()
        uses: actions/upload-artifact@v3
        with:
          name: Detekt Results
          path: |
            ${{ github.workspace }}/**/build/reports/detekt/detekt.*
            ${{ github.workspace }}/build/reports/detekt/merge.*

      - name: Fail if Detekt is missing merged report or has warnings.
        if: success() || failure()
        run: |
          mergedReport=build/reports/detekt/merge.xml
          if [ ! -f "${mergedReport}" ]; then # -f: Path exists and is regular file.
            echo "Detekt report file '${mergedReport}' does not exist."
            exit 2
          fi
          count=$(grep --count '<file name=' "${mergedReport}" || true) 
          if [ $count != 0 ]; then 
            echo "There were $count Detekt failures in '${mergedReport}'."
            exit 3
          fi

      - name: Publish "Code scanning results / detekt".
        uses: github/codeql-action/upload-sarif@v2
        if: success() || failure()
        with:
          sarif_file: ${{ github.workspace }}/build/reports/detekt/merge.sarif
