name: Record Screenshots
on:
  workflow_dispatch
concurrency:
  # Documentation suggests ${{ github.head_ref }}, but that's only available on pull_request/pull_request_target triggers, so using ${{ github.ref }}.
  # On master, we want all builds to complete even if merging happens faster to make it easier to discover at which point something broke.
  # More info: https://stackoverflow.com/a/68422069/253468:
  group: ${{ github.ref == 'refs/heads/master' && format('record-master-{0}', github.sha) || format('record-{0}', github.ref) }}
  cancel-in-progress: true
jobs:
  record:
    name: 📸 Record Screenshots
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Set up JDK 11.
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Set up Android SDK.
        uses: android-actions/setup-android@v2

      - name: Install Android SDK components
        run: |
          # Uninstall NDK, because it's not used and it emits a warning:
          # Warning: Observed package id 'ndk;21.4.7075529' in inconsistent location '/usr/local/lib/android/sdk/ndk-bundle' (Expected '/usr/local/lib/android/sdk/ndk/21.4.7075529')
          echo sdkmanager --uninstall "ndk;21.4.7075529"
          sdkmanager --uninstall "ndk;21.4.7075529"
          # The following are already done by setup-android@v2 action:
          # sdkmanager --install "cmdline-tools;latest"
          # sdkmanager --install "tools"
          # sdkmanager --install "platform-tools"
          # Install Android API used to build the project.
          echo sdkmanager --install "platforms;android-23"
          sdkmanager --install "platforms;android-23"

      - name: Checkout ${{ github.ref }} branch in ${{ github.repository }} repository.
        uses: actions/checkout@v2
        with:
          lfs: true

      - name: LS
        run: |
          ls -la feature/configuration/src/test/snapshots/images

      - name: Record Screenshots
        run: >
          ./gradlew
          --no-daemon
          --no-build-cache
          --stacktrace
          recordPaparazziDebug
          -Pnet.twisterrob.build.screenshot-tests=true

      - name: LS
        run: |
          ls -la feature/configuration/src/test/snapshots/images

      - name: Commit screenshots
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git status
          git add '**/src/test/snapshots/images/*.png'
          git status
          git commit -m "Update screenshots"
          git status
          git push
          git status
 
      - name: Upload "Screenshot Record Results".
        if: success() || failure()
        uses: actions/upload-artifact@v2
        with:
          name: Screenshot Record Results
          path: |
            ${{ github.workspace }}/**/src/test/snapshots/images/*.png
            ${{ github.workspace }}/**/build/reports/tests/*/
            ${{ github.workspace }}/**/build/reports/paparazzi/
            ${{ github.workspace }}/**/out/failures/delta-*.png
            ${{ github.workspace }}/**/out/failures/*.png
